<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoadRouterAreasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            // Hà Nội
            ['name' => 'Ba Đình', 'city_province_id' => 1],
            ['name' => 'Hoàn Kiếm', 'city_province_id' => 1],
            ['name' => 'Tây Hồ', 'city_province_id' => 1],
            ['name' => 'Long Biên', 'city_province_id' => 1],
            ['name' => 'Cầu Giấy', 'city_province_id' => 1],
            ['name' => 'Đống Đa', 'city_province_id' => 1],
            ['name' => 'Hai Bà Trưng', 'city_province_id' => 1],
            ['name' => 'Hoàng Mai', 'city_province_id' => 1],
            ['name' => 'Thanh Xuân', 'city_province_id' => 1],
            ['name' => 'Sóc Sơn', 'city_province_id' => 1],
            ['name' => 'Đông Anh', 'city_province_id' => 1],
            ['name' => 'Gia Lâm', 'city_province_id' => 1],
            ['name' => 'Nam Từ Liêm', 'city_province_id' => 1],
            ['name' => 'Thanh Trì', 'city_province_id' => 1],
            ['name' => 'Bắc Từ Liêm', 'city_province_id' => 1],
            ['name' => 'Mê Linh', 'city_province_id' => 1],
            ['name' => 'Hà Đông', 'city_province_id' => 1],
            ['name' => 'Sơn Tây', 'city_province_id' => 1],
            ['name' => 'Ba Vì', 'city_province_id' => 1],
            ['name' => 'Phúc Thọ', 'city_province_id' => 1],
            ['name' => 'Đan Phượng', 'city_province_id' => 1],
            ['name' => 'Hoài Đức', 'city_province_id' => 1],
            ['name' => 'Quốc Oai', 'city_province_id' => 1],
            ['name' => 'Thạch Thất', 'city_province_id' => 1],
            ['name' => 'Chương Mỹ', 'city_province_id' => 1],
            ['name' => 'Thanh Oai', 'city_province_id' => 1],
            ['name' => 'Thường Tín', 'city_province_id' => 1],
            ['name' => 'Phú Xuyên', 'city_province_id' => 1],
            ['name' => 'Ứng Hòa', 'city_province_id' => 1],
            ['name' => 'Mỹ Đức', 'city_province_id' => 1],
            // Hải Phòng
            ['name' => 'Hồng Bàng', 'city_province_id' => 2],
            ['name' => 'Ngô Quyền', 'city_province_id' => 2],
            ['name' => 'Lê Chân', 'city_province_id' => 2],
            ['name' => 'Hải An', 'city_province_id' => 2],
            ['name' => 'Kiến An', 'city_province_id' => 2],
            ['name' => 'Đồ Sơn', 'city_province_id' => 2],
            ['name' => 'Dương Kinh', 'city_province_id' => 2],
            ['name' => 'Thuỷ Nguyên', 'city_province_id' => 2],
            ['name' => 'An Dương', 'city_province_id' => 2],
            ['name' => 'An Lão', 'city_province_id' => 2],
            ['name' => 'Kiến Thuỵ', 'city_province_id' => 2],
            ['name' => 'Tiên Lãng', 'city_province_id' => 2],
            ['name' => 'Vĩnh Bảo', 'city_province_id' => 2],
            ['name' => 'Cát Hải', 'city_province_id' => 2],
            ['name' => 'Bạch Long Vĩ', 'city_province_id' => 2],
            // Quảng Ninh
            ['name' => 'Hạ Long', 'city_province_id' => 3],
            ['name' => 'Móng Cái', 'city_province_id' => 3],
            ['name' => 'Cẩm Phả', 'city_province_id' => 3],
            ['name' => 'Uông Bí', 'city_province_id' => 3],
            ['name' => 'Bình Liêu', 'city_province_id' => 3],
            ['name' => 'Tiên Yên', 'city_province_id' => 3],
            ['name' => 'Đầm Hà', 'city_province_id' => 3],
            ['name' => 'Hải Hà', 'city_province_id' => 3],
            ['name' => 'Ba Chẽ', 'city_province_id' => 3],
            ['name' => 'Vân Đồn', 'city_province_id' => 3],
            ['name' => 'Hoành Bồ', 'city_province_id' => 3],
            ['name' => 'Đông Triều', 'city_province_id' => 3],
            ['name' => 'Quảng Yên', 'city_province_id' => 3],
            ['name' => 'Cô Tô', 'city_province_id' => 3],
            // Hà Nam
            ['name' => 'Phủ Lý', 'city_province_id' => 4],
            ['name' => 'Duy Tiên', 'city_province_id' => 4],
            ['name' => 'Kim Bảng', 'city_province_id' => 4],
            ['name' => 'Thanh Liêm', 'city_province_id' => 4],
            ['name' => 'Bình Lục', 'city_province_id' => 4],
            ['name' => 'Lý Nhân', 'city_province_id' => 4],
            // Nam Định
            ['name' => 'Nam Định', 'city_province_id' => 5],
            ['name' => 'Mỹ Lộc', 'city_province_id' => 5],
            ['name' => 'Vụ Bản', 'city_province_id' => 5],
            ['name' => 'Ý Yên', 'city_province_id' => 5],
            ['name' => 'Nghĩa Hưng', 'city_province_id' => 5],
            ['name' => 'Nam Trực', 'city_province_id' => 5],
            ['name' => 'Trực Ninh', 'city_province_id' => 5],
            ['name' => 'Xuân Trường', 'city_province_id' => 5],
            ['name' => 'Giao Thủy', 'city_province_id' => 5],
            ['name' => 'Hải Hậu', 'city_province_id' => 5],
            // Thái Bình
            ['name' => 'Thái Bình', 'city_province_id' => 6],
            ['name' => 'Quỳnh Phụ', 'city_province_id' => 6],
            ['name' => 'Hưng Hà', 'city_province_id' => 6],
            ['name' => 'Đông Hưng', 'city_province_id' => 6],
            ['name' => 'Thái Thụy', 'city_province_id' => 6],
            ['name' => 'Tiền Hải', 'city_province_id' => 6],
            ['name' => 'Kiến Xương', 'city_province_id' => 6],
            ['name' => 'Vũ Thư', 'city_province_id' => 6],
            // Ninh Bình
            ['name' => 'Ninh Bình', 'city_province_id' => 7],
            ['name' => 'Tam Điệp', 'city_province_id' => 7],
            ['name' => 'Nho Quan', 'city_province_id' => 7],
            ['name' => 'Gia Viễn', 'city_province_id' => 7],
            ['name' => 'Hoa Lư', 'city_province_id' => 7],
            ['name' => 'Yên Khánh', 'city_province_id' => 7],
            ['name' => 'Kim Sơn', 'city_province_id' => 7],
            ['name' => 'Yên Mô', 'city_province_id' => 7],
            // Vĩnh Phúc
            ['name' => 'Vĩnh Yên', 'city_province_id' => 8],
            ['name' => 'Phúc Yên', 'city_province_id' => 8],
            ['name' => 'Lập Thạch', 'city_province_id' => 8],
            ['name' => 'Tam Dương', 'city_province_id' => 8],
            ['name' => 'Tam Đảo', 'city_province_id' => 8],
            ['name' => 'Bình Xuyên', 'city_province_id' => 8],
            ['name' => 'Yên Lạc', 'city_province_id' => 8],
            ['name' => 'Vĩnh Tường', 'city_province_id' => 8],
            ['name' => 'Sông Lô', 'city_province_id' => 8],
            // Bắc Ninh
            ['name' => 'Bắc Ninh', 'city_province_id' => 9],
            ['name' => 'Yên Phong', 'city_province_id' => 9],
            ['name' => 'Quế Võ', 'city_province_id' => 9],
            ['name' => 'Tiên Du', 'city_province_id' => 9],
            ['name' => 'Từ Sơn', 'city_province_id' => 9],
            ['name' => 'Thuận Thành', 'city_province_id' => 9],
            ['name' => 'Gia Bình', 'city_province_id' => 9],
            ['name' => 'Lương Tài', 'city_province_id' => 9],
            // Hà Giang
            ['name' => 'Hà Giang', 'city_province_id' => 10],
            ['name' => 'Đồng Văn', 'city_province_id' => 10],
            ['name' => 'Mèo Vạc', 'city_province_id' => 10],
            ['name' => 'Yên Minh', 'city_province_id' => 10],
            ['name' => 'Quản Bạ', 'city_province_id' => 10],
            ['name' => 'Vị Xuyên', 'city_province_id' => 10],
            ['name' => 'Bắc Mê', 'city_province_id' => 10],
            ['name' => 'Hoàng Su Phì', 'city_province_id' => 10],
            ['name' => 'Xín Mần', 'city_province_id' => 10],
            ['name' => 'Bắc Quang', 'city_province_id' => 10],
            ['name' => 'Quang Bình', 'city_province_id' => 10],
            // Cao Bằng
            ['name' => 'Cao Bằng', 'city_province_id' => 11],
            ['name' => 'Bảo Lâm', 'city_province_id' => 11],
            ['name' => 'Bảo Lạc', 'city_province_id' => 11],
            ['name' => 'Thông Nông', 'city_province_id' => 11],
            ['name' => 'Hà Quảng', 'city_province_id' => 11],
            ['name' => 'Trà Lĩnh', 'city_province_id' => 11],
            ['name' => 'Trùng Khánh', 'city_province_id' => 11],
            ['name' => 'Hạ Lang', 'city_province_id' => 11],
            ['name' => 'Quảng Uyên', 'city_province_id' => 11],
            ['name' => 'Phục Hòa', 'city_province_id' => 11],
            ['name' => 'Hòa An', 'city_province_id' => 11],
            ['name' => 'Nguyên Bình', 'city_province_id' => 11],
            ['name' => 'Thạch An', 'city_province_id' => 11],
            // Lào Cai
            ['name' => 'Lào Cai', 'city_province_id' => 12],
            ['name' => 'Bát Xát', 'city_province_id' => 12],
            ['name' => 'Mường Khương', 'city_province_id' => 12],
            ['name' => 'Si Ma Cai', 'city_province_id' => 12],
            ['name' => 'Bắc Hà', 'city_province_id' => 12],
            ['name' => 'Bảo Thắng', 'city_province_id' => 12],
            ['name' => 'Bảo Yên', 'city_province_id' => 12],
            ['name' => 'Sa Pa', 'city_province_id' => 12],
            ['name' => 'Văn Bàn', 'city_province_id' => 12],
            // Bắc Kạn
            ['name' => 'Bắc Kạn', 'city_province_id' => 13],
            ['name' => 'Pác Nặm', 'city_province_id' => 13],
            ['name' => 'Ba Bể', 'city_province_id' => 13],
            ['name' => 'Ngân Sơn', 'city_province_id' => 13],
            ['name' => 'Bạch Thông', 'city_province_id' => 13],
            ['name' => 'Chợ Đồn', 'city_province_id' => 13],
            ['name' => 'Chợ Mới', 'city_province_id' => 13],
            ['name' => 'Na Rì', 'city_province_id' => 13],
            // Lạng Sơn
            ['name' => 'Lạng Sơn', 'city_province_id' => 14],
            ['name' => 'Tràng Định', 'city_province_id' => 14],
            ['name' => 'Bình Gia', 'city_province_id' => 14],
            ['name' => 'Văn Lãng', 'city_province_id' => 14],
            ['name' => 'Cao Lộc', 'city_province_id' => 14],
            ['name' => 'Văn Quan', 'city_province_id' => 14],
            ['name' => 'Bắc Sơn', 'city_province_id' => 14],
            ['name' => 'Hữu Lũng', 'city_province_id' => 14],
            ['name' => 'Chi Lăng', 'city_province_id' => 14],
            ['name' => 'Lộc Bình', 'city_province_id' => 14],
            ['name' => 'Đình Lập', 'city_province_id' => 14],
            // Tuyên Quang
            ['name' => 'Tuyên Quang', 'city_province_id' => 15],
            ['name' => 'Lâm Bình', 'city_province_id' => 15],
            ['name' => 'Na Hang', 'city_province_id' => 15],
            ['name' => 'Chiêm Hóa', 'city_province_id' => 15],
            ['name' => 'Hàm Yên', 'city_province_id' => 15],
            ['name' => 'Yên Sơn', 'city_province_id' => 15],
            ['name' => 'Sơn Dương', 'city_province_id' => 15],
            // Yên Bái
            ['name' => 'Yên Bái', 'city_province_id' => 16],
            ['name' => 'Nghĩa Lộ', 'city_province_id' => 16],
            ['name' => 'Lục Yên', 'city_province_id' => 16],
            ['name' => 'Văn Yên', 'city_province_id' => 16],
            ['name' => 'Mù Cang Chải', 'city_province_id' => 16],
            ['name' => 'Trấn Yên', 'city_province_id' => 16],
            ['name' => 'Trạm Tấu', 'city_province_id' => 16],
            ['name' => 'Văn Chấn', 'city_province_id' => 16],
            ['name' => 'Yên Bình', 'city_province_id' => 16],
            // Thái Nguyên
            ['name' => 'Thái Nguyên', 'city_province_id' => 17],
            ['name' => 'Sông Công', 'city_province_id' => 17],
            ['name' => 'Định Hóa', 'city_province_id' => 17],
            ['name' => 'Phú Lương', 'city_province_id' => 17],
            ['name' => 'Đồng Hỷ', 'city_province_id' => 17],
            ['name' => 'Võ Nhai', 'city_province_id' => 17],
            ['name' => 'Đại Từ', 'city_province_id' => 17],
            ['name' => 'Phổ Yên', 'city_province_id' => 17],
            ['name' => 'Phú Bình', 'city_province_id' => 17],
            // Phú Thọ
            ['name' => 'Việt Trì', 'city_province_id' => 18],
            ['name' => 'Phú Thọ', 'city_province_id' => 18],
            ['name' => 'Đoan Hùng', 'city_province_id' => 18],
            ['name' => 'Hạ Hòa', 'city_province_id' => 18],
            ['name' => 'Thanh Ba', 'city_province_id' => 18],
            ['name' => 'Phù Ninh', 'city_province_id' => 18],
            ['name' => 'Yên Lập', 'city_province_id' => 18],
            ['name' => 'Cẩm Khê', 'city_province_id' => 18],
            ['name' => 'Tam Nông', 'city_province_id' => 18],
            ['name' => 'Lâm Thao', 'city_province_id' => 18],
            ['name' => 'Thanh Sơn', 'city_province_id' => 18],
            ['name' => 'Thanh Thủy', 'city_province_id' => 18],
            ['name' => 'Tân Sơn', 'city_province_id' => 18],
            // Bắc Giang
            ['name' => 'Bắc Giang', 'city_province_id' => 19],
            ['name' => 'Yên Thế', 'city_province_id' => 19],
            ['name' => 'Tân Yên', 'city_province_id' => 19],
            ['name' => 'Lạng Giang', 'city_province_id' => 19],
            ['name' => 'Lục Nam', 'city_province_id' => 19],
            ['name' => 'Lục Ngạn', 'city_province_id' => 19],
            ['name' => 'Sơn Động', 'city_province_id' => 19],
            ['name' => 'Yên Dũng', 'city_province_id' => 19],
            ['name' => 'Việt Yên', 'city_province_id' => 19],
            ['name' => 'Hiệp Hòa', 'city_province_id' => 19],
            // Hòa Bình
            ['name' => 'Hòa Bình', 'city_province_id' => 20],
            ['name' => 'Đà Bắc', 'city_province_id' => 20],
            ['name' => 'Kỳ Sơn', 'city_province_id' => 20],
            ['name' => 'Lương Sơn', 'city_province_id' => 20],
            ['name' => 'Kim Bôi', 'city_province_id' => 20],
            ['name' => 'Cao Phong', 'city_province_id' => 20],
            ['name' => 'Tân Lạc', 'city_province_id' => 20],
            ['name' => 'Mai Châu', 'city_province_id' => 20],
            ['name' => 'Lạc Sơn', 'city_province_id' => 20],
            ['name' => 'Yên Thủy', 'city_province_id' => 20],
            ['name' => 'Lạc Thủy', 'city_province_id' => 20],
            // Sơn La
            ['name' => 'Sơn La', 'city_province_id' => 21],
            ['name' => 'Quỳnh Nhai', 'city_province_id' => 21],
            ['name' => 'Thuận Châu', 'city_province_id' => 21],
            ['name' => 'Mường La', 'city_province_id' => 21],
            ['name' => 'Bắc Yên', 'city_province_id' => 21],
            ['name' => 'Phù Yên', 'city_province_id' => 21],
            ['name' => 'Mộc Châu', 'city_province_id' => 21],
            ['name' => 'Yên Châu', 'city_province_id' => 21],
            ['name' => 'Mai Sơn', 'city_province_id' => 21],
            ['name' => 'Sông Mã', 'city_province_id' => 21],
            ['name' => 'Sốp Cộp', 'city_province_id' => 21],
            ['name' => 'Vân Hồ', 'city_province_id' => 21],
            // Điện Biên
            ['name' => 'Điện Biên Phủ', 'city_province_id' => 22],
            ['name' => 'Mường Lay', 'city_province_id' => 22],
            ['name' => 'Mường Nhé', 'city_province_id' => 22],
            ['name' => 'Mường Chà', 'city_province_id' => 22],
            ['name' => 'Tủa Chùa', 'city_province_id' => 22],
            ['name' => 'Tuần Giáo', 'city_province_id' => 22],
            ['name' => 'Điện Biên', 'city_province_id' => 22],
            ['name' => 'Điện Biên Đông', 'city_province_id' => 22],
            ['name' => 'Mường Ảng', 'city_province_id' => 22],
            ['name' => 'Nậm Pồ', 'city_province_id' => 22],
            // Lai Châu
            ['name' => 'Lai Châu', 'city_province_id' => 23],
            ['name' => 'Tam Đường', 'city_province_id' => 23],
            ['name' => 'Mường Tè', 'city_province_id' => 23],
            ['name' => 'Sìn Hồ', 'city_province_id' => 23],
            ['name' => 'Phong Thổ', 'city_province_id' => 23],
            ['name' => 'Than Uyên', 'city_province_id' => 23],
            ['name' => 'Tân Uyên', 'city_province_id' => 23],
            ['name' => 'Nậm Nhùn', 'city_province_id' => 23],
        ];

        DB::table('areas')->insert($districts);

    }
}
